[package]
name = "vrename"
version = "1.0.0"
edition = "2021"
authors = ["John DiSanti"]
description = "Batch rename files with your preferred text editor"
license-file = "COPYING"

[dependencies]
anyhow = "1.0.86"
tempfile = "3.12.0"
